# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# https://github.com/schwa/MetalSprockets-Examples/actions

name: Swift
on:
    push:
    pull_request:
jobs:
    swift-build-26:
        env:
            XCODE_VERSION: "latest-stable"
        runs-on: macos-15 # macos-latest
        steps:
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: ${{ env.XCODE_VERSION }}
            - uses: actions/checkout@v3
            - name: Download MetalToolchain
              run: xcodebuild -downloadComponent MetalToolchain
            - name: Trust plugins
              run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
            - run: swift build -v
              working-directory: Packages/MetalSprocketsExamples
            - run: swift test -v
              working-directory: Packages/MetalSprocketsExamples

    xcode-build-26:
        env:
            XCODE_VERSION: "latest-stable"
            XCODE_PROJECT: "MetalSprockets-Examples.xcodeproj"
            XCODE_SCHEME: "MetalSprockets-Examples"
            XCODE_CONFIGURATION: "Release"
        runs-on: macos-15 # macos-latest
        steps:
            - uses: maxim-lobanov/setup-xcode@v1
              with:
                  xcode-version: ${{ env.XCODE_VERSION }}
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Download MetalToolchain
              run: xcodebuild -downloadComponent MetalToolchain
            - run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidation -bool YES
            - run: |
                  xcodebuild \
                    -project "${{ env.XCODE_PROJECT }}" \
                    -scheme "${{ env.XCODE_SCHEME }}" \
                    -configuration "${{ env.XCODE_CONFIGURATION }}" \
                    -destination "generic/platform=macOS" \
                    -skipPackagePluginValidation \
                    -skipMacroValidation \
                    build \
                    ARCHS=arm64 \
                    ONLY_ACTIVE_ARCH=NO \
                    CODE_SIGNING_ALLOWED=NO
